### ISSUE TITLE
Empty DOM element converted to self closing tag

### ISSUE THREAD

**Issue by lusiakpurnama** [haensl/gulp-embed-svg#39]
Hi, I got this issue where if I have an empty tag, your plugin will convert it to self closing tag. For example:
```
<i class="fas fa-check"></i>
<img src="filename.svg" />
```

Will become:
```
<i class="fas fa-check" />
<svg>svg content</svg>
```

And then in chrome it renders to:
```
<i class="fas fa-check">
  <svg>svg content</svg>
</i>
```

Is there a way to prevent this?

**Comment by haensl** [comment]
Hi @lusiakpurnama,

have you tried using [XML mode](https://github.com/haensl/gulp-embed-svg#xmlmode)?

**Comment by lusiakpurnama** [comment]
@haensl seems the xml mode is true by default.
I just tried to set it to `false`, and it works.

Though now there is another issue I'm having. I'm using your plugin to embed svg to liquid templates for shopify.
But then if there is a liquid expression in any html tag, the plugin seems to try to "correct" the value. For example:
```
<div {% if settings.some_data != blank %}data-some="{{ settings.some_data }}"{% endif %}>some div</div>
```

It becomes:
```
<div {%="" if="" settings.some_data="" !="blank" %}data-some="{{ settings.some_data }}" endif="" %}="">some div</div>
```

This is probably nothing to do with your plugin though cause I tried this plugin also does that:
https://github.com/viktorlarsson/gulp-inject-svg
Just want to mention, I probably cannot use your plugin for uncompiled html templates 😄

**Comment by haensl** [comment]
Hi @lusiakpurnama,

> I probably cannot use your plugin for uncompiled html templates

Maybe your build flow allows for reordering so that templates are compiled _before_ SVGs are inserted?

**Comment by lusiakpurnama** [comment]
Hi @haensl,
I cannot do that. Since you are asking that I suppose you don't know Shopify?
It's an e-commerce CMS system, I think kind of like wordpress but for selling products.
And they have their own templating language called Liquid.

So what I'm working on is the theme for the shop, kind of like theme for wordpress.
What I'm doing currently is optimising the theme, reducing the stuff that Shopify need to compile, so I inject svg using gulp instead of using Liquid function to inject svg on compile in the store.

**Comment by benwakeford** [comment]
Hi there, I have a similar issue where I'm adding SVGs into Wordpress template files (which use PHP).

The actual embedding of the SVG works great, but the plugin is modifying the entire PHP page. So, for example:

`<?php wp_head(); ?>`

Becomes

`<!--?php wp_head(); ?-->`

Which makes the file unreadable by the server, especially when multiplied across all other php tags in the file.

Is there any way of running the plugin so it only touches the elements of the page within <svg></svg> tags, and leaves the rest of the page alone?

Thanks in advance!
