### ISSUE TITLE
Plugin is modifying PHP code

### ISSUE THREAD

**Issue by benwakeford** [haensl/gulp-embed-svg#42]
Hi there, I have an issue where I'm trying to embed SVGs into Wordpress template files (which use PHP).

The actual embedding of the SVG works great, but the plugin is also making other unwanted changes to the rest of the page. So, for example:

`<?php wp_head(); ?>`

Becomes

`<!--?php wp_head(); ?-->`

Which makes the file unreadable by the server, especially when multiplied across all the other php tags in the file.

Is there any way of running the plugin so it only edits the elements of the page within <img "*.svg" /> tags, and leaves the rest of the page alone?

Thanks in advance!

**Comment by haensl** [comment]
Hi @benwakeford,

I think the problem lies within the order or things: the plugin uses [cheerio](https://github.com/cheeriojs/cheerio) which in turn uses [htmlparser](https://github.com/fb55/htmlparser2/) under the hood and expects to be given HTML input, i.e. the result of rendering the PHP template. If you can re-order the steps so that SVGs are embeded _after_ PHP is rendered to HTML it should work.

**Comment by benwakeford** [comment]
Hi @haensl, thanks for the swift reply, appreciated.

Wordpress' PHP templates are rendered at runtime, so it's a no-go to pre-render them within Gulp, unfortunately.

I wonder if there's a way to narrow the scope of what htmlparser actually parses?

**Comment by haensl** [comment]
Hi @benwakeford,

> I wonder if there's a way to narrow the scope of what htmlparser actually parses? (or ignore PHP tags for that matter)

There sure is. At least usually. I'm not much of a PHP/Wordpress dude myself, so I don't know about that platform, but in JavaScript it's in your control what you hand to `gulp` as input.

**Comment by benwakeford** [comment]
Cheers @haensl, that's what I was thinking. Having looked into the dependancies further, I now see why they are html/js focused and that server-side code won't work out of the box.

Will have a think about how to get around it.

Thanks for your help

**Comment by benwakeford** [comment]
Just to follow up for anyone that finds this with a similar problem, I decided to skip the Gulp stage and embed the SVG into the HTML at runtime using:

```
<?php echo file_get_contents( get_stylesheet_directory_uri() . '/img/file.svg' ); ?>
```

Would have been nice to have the SVG baked in from the start to lighten the server load, but this is a suitable compromise for me considering time constraints.

The SVG files are still optimised within Gulp, and if a Wordpress caching plugin is used to save the rendered page, it ends up being pretty much the same end result for a user anyhow.

**Comment by benwakeford** [comment]
One more follow-up: for anyone wanting to embed SVGs into their server side template files, @lusiakpurnama has written a nice gulp task that does the job
